### ISSUE TITLE
Unexpected input 'args', valid inputs are ['']

### ISSUE THREAD

**Issue by dotherightthing** [montudor/action-zip#6]
https://github.com/dotherightthing/wpdtrt-anchorlinks/actions/runs/107231135

```
##[warning]Unexpected input 'args', valid inputs are ['']
Run montudor/action-zip@v0.1.0
  with:
    args: zip -qq -r ./release.zip ./release
```

A warning is issued but the step does complete.

Workflow: https://github.com/dotherightthing/wpdtrt-npm-scripts/blob/master/config/.github/workflows/build-release-tagged.yml

**Comment by montudor** [comment]
I am sorry I didn't see this sooner. I assume this issue is fixed judging from the related issue?

**Comment by dotherightthing** [comment]
Hi, no problem. The `unexpected input` warning was not the cause of the failing build, but it still appears as a warning. For example: https://github.com/dotherightthing/wpdtrt-gallery/actions/runs/107246399

**Comment by dotherightthing** [comment]
Hmm, it seems that it's not possible to drill down into previous build logs. I'll update this issue if I can reproduce this issue with an accompanying log.

**Comment by montudor** [comment]
I believe I need to create an action.yml file for this action - this was not required when I originally released this. I'll get that sorted soon.

**Comment by dotherightthing** [comment]
Cool, thanks.

**Comment by montudor** [comment]
This should be fixed in the latest release, you will need to update your action to use `montudor/action-zip@v0.1.1`. If you have any issues please let me know.
